Upgrade to Nuxt 3.12.4 and Vue 3.2.47
adyen-examples/adyen-vue-online-payments pull request #229
Opened 2024-08-23 13:40 UTC by gcatanese

Upgrade of the underlying frameworks to address a major vulnerability. 

This PR has involved a major refactoring as Nuxt3 is completely different:

- implemented in Typescript
- refactor all Vue pages
- implemented server-side APIs as API Routes
- removed unnecessary dependencies (Express, dotenv, crossenv)
- mode assets to `public` folder

2024-08-26 10:03 UTC, Kwok-he-Chu requested changes
@gcatanese Nice work!

* [ ] `gitpod.yml` is still using port 8080, let's make sure it's changed to port 3000 
* [ ] Double check if the `npm run dev` still applies when spinning-up this repo in gitpod

2024-08-26 10:03 UTC, Kwok-he-Chu commented on server/api/webhooks/notifications.post.js
> +function consumeEvent(notification) {
Mark function as async, we use `await consumeEvent(notification)` earlier

2024-08-26 10:03 UTC, Kwok-he-Chu commented on server/api/webhooks/notifications.post.js
> +    console.log('merchantReference:' + merchantReference + " eventCode:" + eventCode);
nit: Use consistent (double quotes) `"` during string concatenation

2024-08-27 08:54 UTC, gcatanese commented on plugins/adyen-web.client.ts
> +export default defineNuxtPlugin(() => {
Not really. I have refactored to import the Adyen Drop-in CSS in the Nuxt configuration (no need to create a plugin).

2024-08-27 09:27 UTC, gcatanese commented
Thanks @Kwok-he-Chu, I have addressed your comments, please have final look. Tnx

2024-08-27 10:15 UTC, Kwok-he-Chu approved these changes
Minor thing: When gitpod spins-up, the user is prompted with `Nuxt collects completely anonymous data about usage.` Users have to answer with `yes`/`no` in the terminal, can we somehow add this flag so that it defaults to `no`?

See screenshot:
<img width="477" alt="image" src="https://github.com/user-attachments/assets/ea7228bc-b6c7-49f7-a7aa-61a9a3f1c769">

2024-08-27 11:01 UTC, gcatanese commented
> Minor thing: When gitpod spins-up, the user is prompted with `Nuxt collects completely anonymous data about usage.` Users have to answer with `yes`/`no` in the terminal, can we somehow add this flag so that it defaults to `no`?
> 
Yes, well spotted, I have disabled the `telemetry`

2024-08-27 11:02 UTC, merged